[project]
name = "fantasy-ranks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Matt Busche", email = "mrbusche@gmail.com" }]
requires-python = ">=3.13"
dependencies = ["espn-api>=0.46.0", "python-dotenv>=1.0.1", "requests>=2.34.2"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.6",
]


[project.scripts]
fantasy-ranks = "fantasy_ranks:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = [".", "scripts"]
